### ISSUE TITLE
hermes.py && store.py

### ISSUE THREAD

**Issue by aress31** [ephracis/hermes#1]
Hi,
I've noticed few issues with your code the first one is just that you forgot to remove the comment in the hermes.py file line 179 and 180:
        #print "constructing list of apps"
        #browse(args, api, apps)
The second one is for the download of the apps in store.py line 199 and 200:
               sys.stdout.write("\rfetching app list in category {:<50} {:6.2f}% {} ".format(cat_str, 100.0 \* i / num, animation[animation_pos % len(animation)]))
           sys.stdout.flush() 
The python interpreter return as error: NameError: global name 'sys' is not defined
When I tryed to comment those lines I got this error which is located in store.py for the function getApps:
               NameError: global name 'animate' is not defined
Didn't manage to make this program work yet. BUt hopefully if you can fix those errors that should work. My knowledge in Python is pretty basic otherwize I would have taken care of thoses mistakes myself.
Best regards and thanks for this program.

**Comment by ephracis** [comment]
Thanks for the info. I have changed the code. Unfortunately I left it in a bit of a mess after having issues with Google Play and I didn't want to run every piece of code at every run. So this is why some of the code was commented out when it shouldn't have been, really.

Hopefully these changes will fix your issues. If you find more stuff that needs to be fixed or you have any improvements, please send me a pull request with the changes and I'll merge them into the project.

**Comment by aress31** [comment]
Well, thank you once more.
I don't really know how to use github I have created an account but I am
still strugling to figure out how it works (system of pulling...).
An other issue I found is tha

2015-03-23 12:26 GMT+00:00 Christoffer Brodd-Reijer <
notifications@github.com>:

**Comment by aress31** [comment]
Well, thank you once more.
I don't really know how to use github I have created an account but I am
still strugling to figure out how it works (system of pulling...).
An other issue I found is that you have forgotten this import in store.py:
    from output import *
After that an other issue appeared I think it is relared to the interaction
with the google-play library I copy you the text:
hermes 0.1
by ephracis

looking for cache
no cache found
logging in to play store
constructing list of apps
fetching app list in category
BUSINESS/apps_topselling_free:                       6.17% | Traceback
(most recent call last):
  File "hermes.py", line 198, in <module>
    main()
  File "hermes.py", line 180, in main
    browse(args, api, apps)
  File "/root/Desktop/hermes-master/store.py", line 204, in browse
    getApps(gpapi, category, subcategory, apps, args.limit, args.offset)
  File "/root/Desktop/hermes-master/store.py", line 152, in getApps
    details = gpAPI.details(app.docid)
  File "/root/Desktop/hermes-master/googleplay-api-master/googleplay.py",
line 197, in details
    message = self.executeRequestApi2(path)
  File "/root/Desktop/hermes-master/googleplay-api-master/googleplay.py",
line 171, in executeRequestApi2
    message = googleplay_pb2.ResponseWrapper.FromString(data)
  File
"/usr/local/lib/python2.7/dist-packages/protobuf-2.6.1-py2.7.egg/google/protobuf/internal/python_message.py",
line 583, in FromString
    message.MergeFromString(s)
  File
"/usr/local/lib/python2.7/dist-packages/protobuf-2.6.1-py2.7.egg/google/protobuf/internal/python_message.py",
line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.

Hopefully it is one of the last issue :)
Cheers,
Alexandre

2015-03-23 13:46 GMT+00:00 Alexandre Teyar alexandre.teyar@gmail.com:

**Comment by ephracis** [comment]
First, welcome to Git and Github. If you want to learn more about the workflow and pull requests in particular (which is a wonderful way to work), see this link: https://help.github.com/articles/using-pull-requests/

Secondly, it would be best if you open a new issue next time you find more problems. When you reply to this email you will just continue to build upon the first issue (which has already been closed).

Moving on to your last email, it seems that the problem is that Google has put in a defense against automatic crawlers such as hermes. After a number of subsequent requests they show a captcha challenge. I have released version 0.2 which adds an evasion technique to try to get around this by waiting a random amount of time and then do a re-login. This should get around their defense. You will see when evasion is active by a blinking !.

I have not had time to test the best time to wait, but you can specify the approximate time by using the --evasion flag when you start hermes. The default value is 30 seconds. Beware that it is only approximate. I fuzz the value a little bit in the code to make it harder for Google to detect our evasion.

**Comment by AresS31** [comment]
Hi,

It seems that you forgot to upload your new source code with the evasion
technique in your release 0.2 :)

2015-03-24 10:03 GMT+00:00 Christoffer Brodd-Reijer <
notifications@github.com>:
